name: todo_mazic
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  syncfusion_flutter_calendar: ^18.4.42
  syncfusion_localizations: ^18.4.42
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  cupertino_icons: ^1.0.1
  sembast: ^2.4.9
  date_time_picker: ^2.0.0
  path_provider: ^1.6.27
  flutter_material_color_picker: ^1.0.5
  parallax_image: ^0.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-VariableFont_wdth,wght.ttf
